services:
  node:
    image: node:22
    user: node
    working_dir: /home/node
    command: tail -f /dev/null
    ports:
      - 3000-3009:3000-3009
    volumes:
      - ../framework:/home/node/framework
      - ../eslint:/home/node/eslint

  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
