services:
  node:
    image: node:22
    user: node
    working_dir: /home/node/ape-framework
    volumes:
      - ../..:/home/node/ape-framework
    depends_on:
      wait-for-services:
        condition: service_completed_successfully

  maildev:
    image: maildev/maildev

  wait-for-services:
    image: mattsyms/wait-for
    command: maildev:1025 maildev:1080 -t 30
    depends_on:
      maildev:
        condition: service_started
